### ISSUE TITLE
RefreshedConnectionsUI - localisation error

### ISSUE THREAD

**Issue by villosoph** [scottdurow/SparkleXrm#103]
I tried to use the managed Solution for RefreshedConnectionsUI in my german Dynamics CRM 2016 Installation. Now if i load the form with the webressource on I get an error message saying:

_Could not load resource file
'<my Dynamics System URL>/WebRessources/con_js/Res.metadata_1031.js'. Please contact your System Administrator.

error:_

I guess this is because the resource file for german localisation Res.metadata_1031.js is missing (not part of the managed solution). How can I add a german ressource file for this solution? or is it to be included into the managed solution? Or is there a fallback way missing to Display everything in english if no localisation is available?

Attached I provide a german translation for the localisation for 1031

**Comment by scottdurow** [comment]
Hi - you can add your translation file as an unmanaged webresource and it will pick it up just fine.

I agree - it does need to fall back to English if no translation available.
