### ISSUE TITLE
CRM Editable Grid read only

### ISSUE THREAD

**Issue by sameer678** [scottdurow/SparkleXrm#107]
Hi Scott,

I am working on Editable Grid. I was able to create grid successfully. I have few queries.
I want My Grid should be Editable except few columns that should be read only.
Lookup field Like: Created By and date field Created On.

I don't want to achieve this by showing any validation. Just want to disable fields.

I can't see any column level setting. SparkleXRM has editable setting available only at grid level.

Also I want to make the row or Column clickable. It should open particular record. Do i have to capture row event, Construct URL and Open?

Thanks!

**Comment by scottdurow** [comment]
You can selectively add editors to different columns and leave the others read only - see https://github.com/scottdurow/SparkleXrm/blob/master/SparkleXrmSource/Client/ContactEditor/Views/ContactEditorView.cs#L74

You can also use the 'BindReadOnlyColumn' method on the binder. 

The main difference is using the default formatters will use the formatted values that come back from the fetchxml - but if you use the Editor Binders then the value can be changed and will be re-formatted accordingly (e.g. numeric/dates etc).
Hope this helps

**Comment by sameer678** [comment]
Thanks Scott..It worked
