### ISSUE TITLE
Default value and validation

### ISSUE THREAD

**Issue by sameer678** [scottdurow/SparkleXrm#108]
Hi Scott,

1) I have added datetime field on form. I want to set it default to 3 Pm . Date should be blank. Is this possible? I am able to set by default when view model is initialized but it will be removed after reset.
  
                            

2) I have created editable grid and added required field validation. It is firing but it is not working properly. It gives old value in validationbinder view model.

 public static ValidationRules Subject(ValidationRules rules, object viewModel, object dataContext)
        {

            Email self = (Email)viewModel;
            return rules
                    .AddRule("Subject is required.", delegate(object value)
                    {
                        string subjectFound= Knockout.UnwrapObservable<string>(self.Subject);
                        bool isValid=false;
                        if (String.IsNullOrEmpty(subjectFound))
                            isValid = true;
                        return isValid;
                    });

        }

**Comment by scottdurow** [comment]
Hi!

1) I've just added support for a default time on the date picker (https://github.com/scottdurow/SparkleXrm/commit/3d1d68400bf842a606882cbbf603d78e9f5663c8) I'll let you know when I've created a release with this capability included. Probably later this week.

2) The Rule will fire first when the cell is edited on the grid and then when the edit is committed. The value passed to the function will be the initial value on the first time and then the updated value the second time - in your code you are getting the Subject from the view Model which means you'll get the non-committed value - try using the value passed to the rule.

**Comment by KK1674** [comment]
Thanks Scott. I fixed this same day i have posted question.. Sorry i didn't update.

Still default time issue is pending. I can do default date time but need to set just default time.. Is there any progress on this? Please update.

**Comment by sameer678** [comment]
Thanks Scott. I fixed this same day i have posted question.. Sorry i didn't update.

Still default time issue is pending. I can do default date time but need to set just default time.. Is there any progress on this? Please update.

**Comment by scottdurow** [comment]
There is now an Hour and Minute option on the datetime form field binding - see https://github.com/scottdurow/SparkleXrm/blob/3d1d68400bf842a606882cbbf603d78e9f5663c8/SparkleXrmSource/DebugWeb/WebResources/dev1_/html/ContactEditor.htm#L75

**Comment by gkhnmnts** [comment]
I want to only date field . not time field . How do I define ?

**Comment by scottdurow** [comment]
On a grid or form field?

**Comment by gkhnmnts** [comment]
form field.
![untitled](https://user-images.githubusercontent.com/43342216/45801480-aac96900-bcbc-11e8-85bb-1c29556f34da.png)

**Comment by scottdurow** [comment]
Ah - whilst it’s possible on grid fields using a flag - the way to do this on form fields is via css on the specific field’s ID
