### ISSUE TITLE
Can we use EntityDataViewModel with late bound types

### ISSUE THREAD

**Issue by CommonDialog** [scottdurow/SparkleXrm#109]
I have a project that requires the use of late bound types.  Is there any issue if I use late bound types with the EventDataViewModel?  Specifically, when you're asked to send the type of the object that will be managed by the EventDataViewModel, would I think pass typeof(Entity)?

**Comment by scottdurow** [comment]
Yes - you can pass typeof(Entity) and it will use late bound types.
