### ISSUE TITLE
Which Visual Studio Should i use

### ISSUE THREAD

**Issue by aboodh95** [scottdurow/SparkleXrm#121]
Hi
i'm tying to open the project but i'm getting this 
![image](https://cloud.githubusercontent.com/assets/12459798/21541379/23e6a85e-cdcf-11e6-9d37-28de2e821178.png)
this is visual studio 2012 i tried to use 2015 but the solution will not open

**Comment by scottdurow** [comment]
You need to use the CRM Developer Toolkit from the CRM2013 SDK - https://msdn.microsoft.com/en-gb/library/hh372957(v=crm.6).aspx

There are now templates that use the latest Dynamics 365 Developer Toolkit at SparkleXrm/SparkleXrmSamples/SparkleXrmTemplateVS2015/

**Comment by scottdurow** [comment]
Note: I will be updating the core SparkleXRM source to use the Dynamics 365 Developer Toolkit once it is out of beta.
