### ISSUE TITLE
Number format issue for some countries

### ISSUE THREAD

**Issue by vishius** [scottdurow/SparkleXrm#122]
Hi,

I found an issue with the numbers parsing function. for some countries, like Germany/italy/Spain, the decimal symbol is ',' and the numberSeparator is '.' and the function replace at the begining the decimal symbol to '.' then removes all numberSeparator in the value, in our case it's '.', so if we have the value <22,10> the function will parse this value to <2210> which is wrong:

> public static class NumberEx
    {
        public static Number Parse(string value, NumberFormatInfo format)
        {
            if (String.IsNullOrEmpty(value))
                return null;
            // Remove spaces
            value = value.Replace(" ", "");
            // Remove groupseparators and substitute the decimal separator
            if (format.DecimalSymbol != ".")
            {
                value = value.Replace(format.DecimalSymbol, ".");
            }
            value = value.Replace(format.NumberSepartor, "");

Maybe we should replace the numberSeparator first before changing the decimal Symbol.
I'm right or I missed something ?
thanks for your answer

BR,
Mehdi

**Comment by scottdurow** [comment]
You are absolutely right - we need to swap those two substitutions around. I'll fix this in the next release.
