### ISSUE TITLE
PageEx.MajorVersion = 2013; // Use the CRM2013/2015 styles throws exception

### ISSUE THREAD

**Issue by larrywelch** [scottdurow/SparkleXrm#125]
I'm new to Sparkle Xrm and like what I see and read.  I tried following the demo and running the hello world example.  I have everything working except the PageEx.MajorVersion throws an exception.  Any ideas?

**Comment by scottdurow** [comment]
What exception is it throwing?

**Comment by larrywelch** [comment]
I determined that the problem was related to mis-matched solution and dlls.  I had installaed the 7.3.0 into the CRM environment but my VS Solutions we're still referencing the 7.2.x version of Sparkle Xrm.  I updated the packages and it now works.
