### ISSUE TITLE
Qunit is missing when I try to debug using the Fiddler approach

### ISSUE THREAD

**Issue by larrywelch** [scottdurow/SparkleXrm#126]
I have successfully run the Hello World example using Fiddler to intercept.  I'm now trying to run the Unit Tests and the IE Debugger is telling me that Qunit can't be found.  Do I need to install that on the CRM Server?

**Comment by scottdurow** [comment]
In your UnitTest.htm you should have a reference to qunit:
` <script src="//code.jquery.com/qunit/qunit-1.18.0.js"></script>`
and the css:
`<link rel="stylesheet" href="//code.jquery.com/qunit/qunit-1.18.0.css">`

They are downloaded directly from jquery.com
