### ISSUE TITLE
Refreshed Connection Solution Problem

### ISSUE THREAD

**Issue by larrywelch** [scottdurow/SparkleXrm#128]
I installed the RefreshedConnectionsUI_1_1_managed.zip file and then navigated to the Connections.htm page.  Using the debugger I see that there are exceptions preventing the page from functioning.  

I have a screen shot of the page and the debugger but I can't seem to add it to the issue.

The errors are:
1. Unspecified error. (Connections.htm(1,1))
2. Unable to get property Entity of undefined or null reference (ClientUI.js(48,242))
3. Unable to get the property 'majorVersion' of undefined or null reference (ClientUI.js(39,47))

I have installed SparkleXrm 7.3.0 on the server.

Any ideas?

**Comment by scottdurow** [comment]
This is because 7.3.0 changed the namespace - I'll recompile and upload the new version.

**Comment by aappddeevv** [comment]
I get an error when trying to import it: The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.
