### ISSUE TITLE
How do you set the page to 1 after loading data into an EntityDataViewModel?

### ISSUE THREAD

**Issue by bkwaz4** [scottdurow/SparkleXrm#129]
I added a second grid to the QuoteLineEditor and after loading, using a fetch, the page is set to the last page in the set.  How do you reset it to page 1?

**Comment by scottdurow** [comment]
Can you post your code - the EntityDataViewModel should always start at page 1

**Comment by scottdurow** [comment]
Closing due to inactvitiy
