### ISSUE TITLE
How to fix the Role(To) column to a fixed value after Connected(To) is filled?

### ISSUE THREAD

**Issue by stevefu8** [scottdurow/SparkleXrm#130]

**Comment by scottdurow** [comment]
Do you want to enforce a specific Role(To) depending on the type of record connected to?

In the `ConnectionViewModel.cs` you can add an on change event like:
```ConnectionEdit.GetValue().Record1Id.Subscribe(Record1Id_OnChange);```

Then the event can set the role id when the record is set:
```private void Record1Id_OnChange(EntityReference value)
{
    // Set the Connection Role
    if (value.LogicalName=="account")
    {
        ConnectionEdit.GetValue().
            Record1RoleId.
            SetValue(new EntityReference(new Guid("someguid"), "connectionrole", "Some Role"));
    }
}
```
