### ISSUE TITLE
Asynchronous problem?

### ISSUE THREAD

**Issue by craigseymour** [scottdurow/SparkleXrm#134]
We're trying to use RetrieveAttributeRequest.  In the browser we get a null response, and in Fiddler we get a valid response.  Is it likely that this is a sync/async issue?  If so, do you have any example code about how to wrap the request to handle the async response?  We can see stuff like BeginExecute() and EndExecute(), but we haven't quite got out heads around what goes where...

**Comment by scottdurow** [comment]
You can call both Sync and Async
For an example of calling Synchronously see https://github.com/scottdurow/SparkleXrm/blob/0081ad475d84e605a6e8bdc0247a7076965ad3b1/SparkleXrmSource/SparkleXrm/Sdk/Metadata/MetadataCache.cs#L125

For an example of calling Request Asynchronously (using BeginExecute and EndExecute) see  https://github.com/scottdurow/SparkleXrm/blob/607bdbafe3550688f480aa83297a536a754aa8ea/SparkleXrmSource/Client/ScheduledJobsEditor/ViewModels/ScheduledJobsEditorViewModel.cs#L402

**Comment by craigseymour** [comment]
Oh, OK, thank you.  Our code is basically identical to your synchronous version.  Must be something else going on then...

**Comment by craigseymour** [comment]
OK.  Cracked it.  The problem is that the current implementation of  [RetrieveAttributeResponse.AttributeMetaData](../blob/master/SparkleXrmSource/SparkleXrm/Sdk/Messages/RetrieveAttributeResponse.cs) only retrieves the OptionSet values (and I think even then only if they're the first node in the response?) - we were looking for one of the other properties.  

So the AttributeMetaData was null, even though the SOAP response has everything in it.

**Comment by scottdurow** [comment]
Ah-ha! Use RetrieveMetadataChangesResponse instead - this should give you all of the attribute metdata.
[MetadataQueryBuilder.cs](https://github.com/scottdurow/SparkleXrm/blob/0081ad475d84e605a6e8bdc0247a7076965ad3b1/SparkleXrmSource/SparkleXrm/Sdk/Metadata/Query/MetadataQueryBuilder.cs) makes it easier to query!

**Comment by craigseymour** [comment]
Will do.  Do you want me to raise a new issue to say that RetrieveAttributeResponse.AttributeMetaData should use the same method as RetrieveMetadataChangesResponse to retrieve the metadata?

**Comment by scottdurow** [comment]
I don't think we need support for this message because it's effectively replaced by RetrieveMetadataChanges - perhaps we can mark it as depreciated?

**Comment by craigseymour** [comment]
I guess - although I'm not sure when looking through messages that I'd naturally pick a message about 'changes' to get the current data.  But that's a platform issue, rather than a SparkleXRM issue, right?

**Comment by scottdurow** [comment]
The [SDK](https://msdn.microsoft.com/library/jj919080.aspx) says "The new classes in the Microsoft.Xrm.Sdk.Metadata.Query namespace and the RetrieveMetadataChangesRequest message in Update Rollup 12 and the December 2012 Service Update provide better options for developers to retrieve just the metadata they need and to detect changes to the metadata over time." 

So I suppose we should read 'better option' as meaning we should use it over the older RetrieveAttributeRequest.

**Comment by craigseymour** [comment]
Ooooh - look at you, reading the manual... :-)  In that case, yes, I would definitely deprecate it!

**Comment by scottdurow** [comment]
👍
