### ISSUE TITLE
Refreshed UI Connections Grid: Field values not visible in the grid even when the values exist in the actual records

### ISSUE THREAD

**Issue by TejalC** [scottdurow/SparkleXrm#140]
We have configured refreshed ui connections grid for a view (let's say view A). Some field values are not showing up in the grid. The field values appear as desired when the same view is browsed using OOB connections grid. Please see the attached screenshot, one showing up the view using Refreshed Connection UI Grid, 
![refreshedconnectionsuifieldvaluesnotvisibleissue](https://cloud.githubusercontent.com/assets/28951047/26449958/b94dc1ea-4172-11e7-9fbf-aca5cbbd0a31.png)

and one using the OOB Connections.
![oobconnectionsgrid](https://cloud.githubusercontent.com/assets/28951047/26449959/b94f1982-4172-11e7-9782-2a4fcbc0a5cb.png)

Please note that we tried to get the grid working using the solution latest at that time (SparkleXRM_7_3_0_managed.zip). But it was not working , so we have used (SparkleXRM_7_2_7_managed.zip). The refreshed connections ui solutions we used was RefreshedConnectionsUI_1_1_managed.zip.

**Comment by scottdurow** [comment]
This is a limitation of the connections grid in that it cannot show values from related entities.
Definitely considering it for a future release.

**Comment by TejalC** [comment]
Okay..Thanks for the help!!
