### ISSUE TITLE
spkl not detecting plugins inheriting from an abstract class.

### ISSUE THREAD

**Issue by davebrown211** [scottdurow/SparkleXrm#142]
I have a base abstract class that directly implements IPlugin, and use that to simplify my plugin development in a particular project I am working on. The issue I am seeing is that the spkl batch files are not finding any plugins unless they directly implement IPlugin, and I can confirm it does work fine when they do.

**Comment by scottdurow** [comment]
Hi, Dave - right you are! 
There is a regex that detects the plugin class names https://github.com/scottdurow/SparkleXrm/blob/master/spkl/SparkleXrm.Tasks/CodeParser.cs#L26

I guess to support custom base classes (I currently have support for the DevelopToolkit base class) we'll need to add an additional parameter on the task. Feel free to fork and send a pull request 😄

**Comment by davebrown211** [comment]
I see how it works now thanks! I can rename the base class "PluginBase" and it should work fine.
