### ISSUE TITLE
Will there be support for WorkflowActivities inheriting from WorkflowActivityBase class included in the CRM developlent toolkit?

### ISSUE THREAD

**Issue by sabrish** [scottdurow/SparkleXrm#146]
Currently spkl only checks for classes inheriting from CodeActivity and not from WorkflowActivityBase. Will there be support to check classes inheriting from WorkflowActivityBase?

**Comment by scottdurow** [comment]
This is similar to https://github.com/scottdurow/SparkleXrm/issues/142

How would you like the name to be configurable - would changing the regex in the spkl.json be ok?

**Comment by sabrish** [comment]
That would be perfect. Would allow users to have their own base class if required and also use spkl.

**Comment by chandrashekharsingh-crm** [comment]
@scottdurow  - Tried with the new classRegex option in spkl.json , still doesn't seems to recognize  Workflow classes derived from custom base class

**Comment by sabrish** [comment]
@scottdurow  - I have the same issue as well. The Init() in CodeParser.cs is called using the regex defined in the code and not using the Regex from spkl.json file.

![image](https://user-images.githubusercontent.com/2657337/29033891-6eca0786-7b8e-11e7-8960-188509937508.png)

**Comment by scottdurow** [comment]
Doh! That's what you get for cutting corners and not writing unit tests!
