### ISSUE TITLE
Do sparkle have some memory or data size restriction ?

### ISSUE THREAD

**Issue by kaitek** [scottdurow/SparkleXrm#158]
![issue](https://user-images.githubusercontent.com/6463920/29659989-a77bb7cc-88c8-11e7-87d8-8354b93e17ff.png)

Hi Scott - I downloaded image with issue we faced a while ago. I think it's IE Issue - sending you for fyi.
Would like to know - do sparkle have some memory or data size restriction ?
Thanks,
Alex

**Comment by scottdurow** [comment]
Hi Alex,
This is a limitation of IE's memory management (https://connect.microsoft.com/IE/feedback/details/1053110/not-enough-storage-is-available-to-complete-this-operation-8007000e-error-when-trying-to-get-a-response-around-100mb-via-ajax)
You'll need to reduce the size of the result set by using paging.

**Comment by kaitek** [comment]
Hi Scott , thank you for reply - in addition I can confirm - no issues in Chrome with 100 MB size.
When we limited paging - no issue in IE.
Alex
