### ISSUE TITLE
spkl: web resource deployment - support regex and path parameters

### ISSUE THREAD

**Issue by FixRM** [scottdurow/SparkleXrm#166]
Usually we need to deploy whole web resource folder and mimic it structure. So it would be nice to have some webpack-like syntax in spkl.json:

//looking for js files
//unique name will be based on folder structure and original file name
"files": [
        {
          "test": /\.js?$/", 
          "uniquename": "new_\[path]\[name].[ext]", 
          "description": ""
        },
]

This way we can add new files to the solution without changing config file

**Comment by scottdurow** [comment]
Do you think it really needs a regex - or would a glob style pattern be ok?
E.g. ```**\*.js```

Then we could simply use the filepath as the uniquename?

**Comment by FixRM** [comment]
Yes, it will solve the problem.

p.s. It will be a honor for me to participate in your project if you want :)

**Comment by scottdurow** [comment]
Great - a pull request would be awesome if you fancy it!

**Comment by FixRM** [comment]
I have some problems with Tests and BuildTask projects. Tools for testing and building VS Extensions are installed. Can you please tell me what I missed?

**Comment by scottdurow** [comment]
What problem are you seeing?

**Comment by FixRM** [comment]
BuildTask project is marked as "incompatible". This usually means that project type or template is not installed.

In Tests projects Microsoft.QualityTools.Testing.Fakes reference is missing. I find some topics say that Fakes can't be used with VS Community Edition. I'll try to upgrade soon

**Comment by scottdurow** [comment]
Fakes are included with Visual Studio Enterprise - https://www.visualstudio.com/vs/compare/

**Comment by FixRM** [comment]
Now tests are ok. Thanks
