### ISSUE TITLE
How is SparkleXrmUI_Dependancies.js created

### ISSUE THREAD

**Issue by larrywelch** [scottdurow/SparkleXrm#174]
How is the SparkleXrmUI_Dependancies.js file created?  I've seen a post somewhere that talks about it but I can't seem to get back to it.

**Comment by scottdurow** [comment]
Details here - https://github.com/scottdurow/SparkleXrm/blob/master/SparkleXrmSource/DebugWeb/WebResources/sparkle_/dependancies/Dependanices%20Google%20Closure%20Compiler.txt
