### ISSUE TITLE
SparkleXrm_0_1_0_managed.zip error when iporting to CRM Online

### ISSUE THREAD

**Issue by peterdawhiz** [scottdurow/SparkleXrm#191]
"You can only import solutions with a package version of 9.0 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier."
![image](https://user-images.githubusercontent.com/1586554/35092284-f68d4326-fc4f-11e7-8672-2e04f8cd7b58.png)

**Comment by scottdurow** [comment]
You'll need to import the most recent version of the SparkleXrm solution with version 9.0 - https://github.com/scottdurow/SparkleXrm/releases
