### ISSUE TITLE
spkl.fakes

### ISSUE THREAD

**Issue by CrmDev23** [scottdurow/SparkleXrm#196]
Hi Scott
Great job (once again)!
With spkl.fakes is it currently possible to mock LINQ queries?
Cheers

**Comment by scottdurow** [comment]
Yes - a Linq query simply get's converted into a RetrieveMultipleRequest and so you just need to add an expectation for that, check the QueryExpressions and return the result.

**Comment by CrmDev23** [comment]
Perfect, thanks Scott!

**Comment by Enielezi** [comment]
Hi Scott,

I am also trying to use Linq with last binding (OrganizationServiceContext().CreateQuery). Using  `pluginPipeline.FakeService.ExpectRetrieveMultiple` throws the error: 
`Fake Organization Service expected 'RetrieveMultiple' but 'Execute' was called`

I tried using `ExpectExecute` with `retrieveMultipleRequest` as delegate is fine but with this we can't return any results. It returns `OrganisationResponse` (casted to `RetrieveMultipleResponse`) which doesn't allow setting `EntityCollection` property, and therefore being unable to get the result entities!
Is there a way to include these results on response of `ExpectExecute` delegate?

**Comment by Enielezi** [comment]
Please ignore previous question, I have managed to get the response with desired EntityCollection entities. Thanks

**Comment by scottdurow** [comment]
Could you post the code you used for reference? Thanks

**Comment by Enielezi** [comment]
Yes sure, this is returning the `returnEntities` collection. Thanks

```
            pluginPipeline.FakeService.ExpectExecute((retrieveMultipleRequest) =>
            {

                if (((QueryExpression)((RetrieveMultipleRequest) retrieveMultipleRequest).Query).EntityName != target.LogicalName)
                    throw new InvalidPluginExecutionException("Wrong entity!");

                var linqResponse = new RetrieveMultipleResponse
                {
                    Results = new ParameterCollection
                    {
                        {"EntityCollection", new EntityCollection(returnEntities)}
                    }
                };
                linqResponse.EntityCollection.EntityName = target.LogicalName;
                return linqResponse;
            });

```
