### ISSUE TITLE
spkl: can't connect with Dynamics 365 (online) instances

### ISSUE THREAD

**Issue by GirijeshD** [scottdurow/SparkleXrm#199]
Could not able connect Dynamics 365 (online) instances from deploy-plugins.bat.. I am using spkl version 1.0.178.1. Connection is well tested by XrmTooling to connect. 
Error Details:
The application terminated with an error.
Metadata contains a reference that cannot be resolved: 'https://disco.https//***
*******.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=8.2'
.
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.R
etrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(Resolve
CallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Metadat
aRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri add
ress, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMet
adata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Bool
ean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TSer
vice](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TSer
vice](Uri serviceUri)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetProxy[TService,TProxy](Confi
guration currentConfig)
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetDiscoveryProxy()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetOrganizationAddress()
   at Microsoft.Crm.Sdk.Samples.ServerConnection.GetServerConfiguration()
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
The remote name could not be resolved: 'disco.https'
Press any key to continue . . .

**Comment by GirijeshD** [comment]
i don't know why its appending https://disco in organisation URL.. Please suggest

**Comment by scottdurow** [comment]
Check that you don’t have an old version of spkl in your packages folder as well as the most up to date one.

**Comment by GirijeshD** [comment]
I uninstalled the most up to date version & tried with two versions 1.0.119.1 & 1.0.1781, still getting an error but this time URL is changed  'https://https//n*******it.crm4.dynamics.com//XRMServices/2011/Discovery.svc?wsdl&sdkversion=8.2'

this time its appending https//.. 
Can you please let me know stable version that use to deploy plugin via deploy-plugins.bat?

**Comment by henrikhannemose** [comment]
This is probably related to Microsoft [removing support for TLS 1.0/1.1 in D365 9.0](https://blogs.msdn.microsoft.com/crminthefield/2017/11/08/dynamics-365-monthly-update-october-2017/).

Try compiling spkl with .NET 4.6.2 ([it worked for us](https://github.com/delegateas/XrmDefinitelyTyped/issues/47) when faced with the same issue). More details from Matt Barbour on [CRM Tip of the Day](https://crmtipoftheday.com/1058/connect-to-version-9-in-your-code/).

**Comment by scottdurow** [comment]
The latest version of spkl (https://www.nuget.org/packages/spkl/1.0.198) is compiled against .NET 4.6.2 and using the latest V9 SDK assemblies - can you make sure you are using this version please?

**Comment by GirijeshD** [comment]
Thanks.. Now Issues has been resolved..

**Comment by iddycol** [comment]
Hi Scott

I have run into this issue today. I have the latest stable versions of spkl and the CRM SDK as far as I know. My project is targeting .NET 4.6.2. Screenshot attached. any suggestions on how to troubleshoot from there?

![spkl_connect](https://user-images.githubusercontent.com/6727875/44401343-b0367500-a591-11e8-85f0-da790be4dfea.png)

**Comment by scottdurow** [comment]
When asked for the server address - only put crm11.dynamics.com

Also - plugins should still be built against 4.5.2 of the .Net framework

**Comment by iddycol** [comment]
aaah - RTFM - That fixed it! Thanks for the prompt reply.

**Comment by MG-89** [comment]
Hello Scott,

I am facing the same issue. 

I am using dynamics 365 on-premise version 9.0. The console app was built using .Net 4.6.2. Any suggestions?

![image](https://user-images.githubusercontent.com/45626575/49510706-78cea880-f8a2-11e8-901b-877dd92e4759.png)

**Comment by scottdurow** [comment]
Hi - this looks like you have a dns issue since the discovery service is returning 19.2168.1.80 but the url is configured for internalcrm.mzectest.org

**Comment by MG-89** [comment]
Thanks Scott,

I raised the issue with our sys admin team and they resolved. Looking forward to using your tool in our development.

**Comment by dillorscroft** [comment]
I suspect you are adding the instance name as well.  Think you need to omit that

**Comment by babakjafari4** [comment]
Dear Scott, I have same problem as this image:
![image](https://user-images.githubusercontent.com/45145997/59148148-4f8e0100-8a1a-11e9-9654-3feeaa324cac.png)
I do it with version 9 of crm coreassemblies too.
thanks for your helping.
