### ISSUE TITLE
Version for D 365 (8.2)

### ISSUE THREAD

**Issue by rajsekhar311** [scottdurow/SparkleXrm#200]
Hi,

Which version of SparkleXrm solution I should install for Dynamics365 (8.2) ? I tried to install 7.2.8 but it is giving the following error.

![image](https://user-images.githubusercontent.com/36291984/36015690-94070726-0d95-11e8-9b0a-500c3a4add43.png)

Please suggest.

Thanks,
Phani.

**Comment by scottdurow** [comment]
This error is happening quite a bit at the moment in lost of places - try again later on. It is due to something go on with the CRM onlne servers.

**Comment by rajsekhar311** [comment]
Ok Scott
