### ISSUE TITLE
Access is denied when running pack+import.bat.

### ISSUE THREAD

**Issue by dimanngo** [scottdurow/SparkleXrm#211]
When I ran pack+import.bat the error "Access is denied" is occurred in stage of solution importing. I’m using Dynamics 365 on premise (v 8.2). When importing manually under the same credentials everything is ok. As well plugins and web resources are deployed successfully using spkl task runner.

...
Solution Packed to '....\CrmCustomization.zip'
Importing solution '...\CrmCustomization.zip'...
..........................Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServic
eFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Access is denied.Detail:

<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/201
1/Contracts">
  <ActivityId>a8b4defc-aa28-43f3-8bd3-94aeafca4f8f</ActivityId>
  <ErrorCode>-2147187707</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>Access is denied.</Message>
  <Timestamp>2018-03-13T07:29:29.2301304Z</Timestamp>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>a8b4defc-aa28-43f3-8bd3-94aeafca4f8f</ActivityId>
    <ErrorCode>-2147187707</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>Access is denied.</Message>
    <Timestamp>2018-03-13T07:29:29.2301304Z</Timestamp>
    <ExceptionSource i:nil="true" />
    <InnerFault>
      <ActivityId>a8b4defc-aa28-43f3-8bd3-94aeafca4f8f</ActivityId>
      <ErrorCode>-2147220970</ErrorCode>
      <ErrorDetails xmlns:d4p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
      <Message>System.UnauthorizedAccessException: Microsoft Dynamics CRM has experienced an error. Reference number for
administrators or support: #8E1F2662</Message>
      <Timestamp>2018-03-13T07:29:29.2301304Z</Timestamp>
      <ExceptionSource i:nil="true" />
      <InnerFault i:nil="true" />
      <OriginalException i:nil="true" />
      <TraceText i:nil="true" />
    </InnerFault>
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>
   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken co
rrelationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext
 executionContext)
   at Microsoft.Crm.Extensibility.InprocessServiceProxy.ExecuteCore(OrganizationRequest request)
   at Microsoft.Crm.Asynchronous.ExecuteSdkMessageOperation.InternalExecute(AsyncEvent asyncEvent)

**Access is denied.**

**Comment by mwnowicki** [comment]
Hi @dimanngo, I have exactly the same problem. How did you solved it?

**Comment by scottdurow** [comment]
Make sure that you enter the correct CRM region - so if you are in Europe then you’ll need to enter crm4.dynamics.com rather than the default crm.dynamics.com

**Comment by mwnowicki** [comment]
Hi Scott,
I use Dynamics CRM on premise. I had 8.1 and I had this problem, then I updated to 8.2, still have the same problem.

I'm able to:
- unpack solution
- deploy-plugins
- deploy-webresources

Not able to:
- pack+import

Creadentials.xml:
----------------------------------------------------------------------------------------------------------------
```
<?xml version="1.0" encoding="utf-8"?>
<Configurations>
  <Configuration>
    <ServerAddress>CRMSERVER:5555</ServerAddress>
    <OrganizationName>CRMDemo</OrganizationName>
    <DiscoveryUri>http://CRMSERVER:5555/XRMServices/2011/Discovery.svc</DiscoveryUri>
    <OrganizationUri>http://crmserver:5555/DynamicsCRMDemo/XRMServices/2011/Organization.svc</OrganizationUri>
    <HomeRealmUri>
    </HomeRealmUri>
    <Credentials>
      <UserName>USER</UserName>
      <Domain>DOMAIN</Domain>
    </Credentials>
    <EndpointType>ActiveDirectory</EndpointType>
    <UserPrincipalName>
    </UserPrincipalName>
  </Configuration>
</Configurations>
```
----------------------------------------------------------------------------------------------------------------

Error which I get:
----------------------------------------------------------------------------------------------------------------
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\SF365\Solution\spkl>"pack+import.bat"
Using 'C:\SF365\packages\spkl.1.0.198\tools\spkl.exe'
spkl Task Runner v1.0.198.1     Tasks v1.0.198.1

(0) Add New Server Configuration (Maximum number up to 9)
(1) Server: CRMSERVER:5555,  Org: CRMDEMO,  User: DOMAIN\USER

Specify the saved server configuration number (1-1) [1] :

Packing & Import Solution
Searching for packager config in 'C:\SF365\Solution\spkl\..'
Using Config 'C:\SF365\Solution'
Target C:\SF365\packages\spkl.1.0.198\tools
Map xml created at 'C:\SF365\packages\Microsoft.CrmSdk.CoreTools.8.2.0.5\content\bin\coretools\packager_map.xml'
Running C:\SF365\packages\spkl.1.0.198\tools\..\..\Microsoft.CrmSdk.CoreTools.8.2.0.5\content\bin\coretools\SolutionPackager.exe /action:Pack /zipfile:"C:\SF365\Solution\solution_1_0_0_0.zip" /folder:"C:\SF365\Solution\package" /packagetype:unmanaged /errorlevel:Verbose /nologo /log:packagerlog.txt /map:packager_map.xml
Reading mapping directives...
<FileToPath map="PluginAssemblies\**\*.*" to="..\..\Plugins\bin\**" />
<FileToPath map="WebResources\*.*" to="..\..\Webresources\Webresources\**" />
<FileToPath map="WebResources\**\*.*" to="..\..\Webresources\Webresources\**" />

Packing C:\SF365\Solution\package to C:\SF365\Solution\solution_1_0_0_0.zip

Processing Component: Entities
 - Account
Reading: C:\SF365\Solution\package\Entities\Account\Entity.xml
Reading: C:\SF365\Solution\package\Entities\Account\FormXml\main\{8448b78f-8f42-454e-8e2a-f8196b0419af}.xml
Reading: C:\SF365\Solution\package\Entities\Account\RibbonDiff.xml
Processing Component: Roles
Processing Component: Workflows
Processing Component: FieldSecurityProfiles
Processing Component: Templates
Processing Component: EntityMaps
Processing Component: EntityRelationships
Reading: C:\SF365\Solution\package\Other\Relationships.xml
Processing Component: optionsets
Processing Component: WebResources
Reading: C:\SF365\Solution\package\WebResources\sf365_\js\checkin.js.data.xml
 - sf365_/js/checkin.js
Mapping: C:\SF365\Solution\package\WebResources\sf365_\js\checkin.js to C:\SF365\Webresources\Webresources\sf365_\js\checkin.js
Reading: C:\SF365\Webresources\Webresources\sf365_\js\checkin.js
Processing Component: SolutionPluginAssemblies
Reading: C:\SF365\Solution\package\PluginAssemblies\SF365Plugins-5CA1154C-853E-E811-966D-000C29A45650\SF365Plugins.dll.data.xml
 - SF365Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3edc1bf3fcb9c6dc
Mapping: C:\SF365\Solution\package\PluginAssemblies\SF365Plugins-5CA1154C-853E-E811-966D-000C29A45650\SF365Plugins.dll to C:\SF365\Plugins\bin\Debug\SF365Plugins.dll
Reading: C:\SF365\Plugins\bin\Debug\SF365Plugins.dll
Processing Component: SdkMessageProcessingSteps
Reading: C:\SF365\Solution\package\SdkMessageProcessingSteps\{5fa1154c-853e-e811-966d-000c29a45650}.xml
Following root components are not defined in customizations:
Solution Packed to 'C:\SF365\Solution\solution_1_0_0_0.zip'
Importing solution 'C:\SF365\Solution\solution_1_0_0_0.zip'...
...............Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Access is denied.Detail:
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>b65d9858-ce66-4045-ae30-b2fe0851d896</ActivityId>
  <ErrorCode>-2147187707</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>Access is denied.</Message>
  <Timestamp>2018-04-13T07:29:02.8845065Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>b65d9858-ce66-4045-ae30-b2fe0851d896</ActivityId>
    <ErrorCode>-2147187707</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>Access is denied.</Message>
    <Timestamp>2018-04-13T07:29:02.8845065Z</Timestamp>
    <ExceptionRetriable>false</ExceptionRetriable>
    <ExceptionSource i:nil="true" />
    <InnerFault>
      <ActivityId>b65d9858-ce66-4045-ae30-b2fe0851d896</ActivityId>
      <ErrorCode>-2147220970</ErrorCode>
      <ErrorDetails xmlns:d4p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
      <Message>System.UnauthorizedAccessException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #D93B3304</Message>
      <Timestamp>2018-04-13T07:29:02.8845065Z</Timestamp>
      <ExceptionRetriable>false</ExceptionRetriable>
      <ExceptionSource i:nil="true" />
      <InnerFault i:nil="true" />
      <OriginalException i:nil="true" />
      <TraceText i:nil="true" />
    </InnerFault>
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>
   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext)
   at Microsoft.Crm.Extensibility.InprocessServiceProxy.ExecuteCore(OrganizationRequest request)
   at Microsoft.Crm.Asynchronous.ExecuteSdkMessageOperation.InternalExecute(AsyncEvent asyncEvent)

Access is denied.
Press any key to continue . . .
```
----------------------------------------------------------------------------------------------------------------

**Comment by mwnowicki** [comment]
Seems that I solve this problem. It was failing because of access rights to 'C:\Program Files\Microsoft Dynamics CRM\CustomizationImport'.
