### ISSUE TITLE
Instrument Plugin - (un)secure config xml

### ISSUE THREAD

**Issue by aelsmore** [scottdurow/SparkleXrm#218]
Running instrument plugin causes issues when there is xml in the (un)secure configuration (see screenshot)

![image](https://user-images.githubusercontent.com/6952441/38356694-50e4e686-38b8-11e8-9263-a2afce314d93.png)

**Comment by scottdurow** [comment]
This issue is fixed in https://www.nuget.org/packages/spkl/1.0.212-beta

**Comment by aelsmore** [comment]
No worries, cheers.
