### ISSUE TITLE
spkl: instrument command generates .cs files in current windows locale, not in UTF-8

### ISSUE THREAD

**Issue by zhaparoff** [scottdurow/SparkleXrm#233]
Hello Scott,

Usually all code files are created and stored by VS with UTF-8 encoding.
But, when I'm running 'spkl instrument' command, .cs files are generated with my windows locale encoding.
I have to run 'Save As...' for each updated file, and choose the UTF-8 encoding again.
This is a bit annoying...

Could UTF-8 be used as default encoding, when regenerating plugin code files with 'instrument' command?

--
Best regards,
Anton

**Comment by mattp65** [comment]
PR submitted that uses the current encoding of the file when saving it.

**Comment by scottdurow** [comment]
Included in https://www.nuget.org/packages/spkl/1.0.233-beta

**Comment by scottdurow** [comment]
This released as https://www.nuget.org/packages/spkl/1.0.370
