### ISSUE TITLE
spkl: Compatibility with 8.2

### ISSUE THREAD

**Issue by pmalecka** [scottdurow/SparkleXrm#237]
Hi Scott,

I am trying to deploy plugins to a 8.2 online organization.
The assembiles have been built using Microsoft.CrmSdk.CoreAssemblies version 8.2.0.5 .

The error I am getting is: 
`Could not load file or assembly 'Microsoft.Crm.Sdk.Proxy, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at SparkleXrm.Tasks.DeployPluginsTask.DeployPlugins(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.DeployPluginsTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Press any key to continue . . .`

It seems that since spkl is built using the newer version of CoreAssemblies, it cannot load the older version of those dependencies when deploying the plugin.

Is there any way I can use the newest version of spkl against my 8.2 org?

Thanks,
Peter

**Comment by gordonjohnston72** [comment]
Did you get an answer to this?

I haven't tried to deploy yet but have hit an error on generating the earlybound class.  The routine is expecting CrmSvcUtil, Version=9.0.0.0

I am experimenting with an existing Plugin assembly that is installed in CRM 2016 on premise.  I actually would like to use 8.2.

Can I configure the version or install an earlier version of spkl?

**Comment by pmalecka** [comment]
Nope no answer, but I figured there are 2 options:
Use an earlier version of the tool (available on NuGet)
Recompile the tool with the older assemblies (just edit packages.config, or use VS Package Manager)

Cheers,
Peter

**Comment by scottdurow** [comment]
Can you try using version 1.0.226 - this should connect to 8.2 and v9 without an issue.
Install-Package spkl -Version 1.0.226

**Comment by CoreySutton** [comment]
@scottdurow @pmalecka I've submitted pull request #262 that appears to fix this issue. I've tested this by deploying a workflow assembly to v8.2 and v9 CRM instances.

**Comment by scottdurow** [comment]
Included in https://www.nuget.org/packages/spkl/1.0.228-beta

**Comment by Sano** [comment]
I'm still seeing this error using 1.0.228-beta

**Comment by scottdurow** [comment]
This is released as https://www.nuget.org/packages/spkl/1.0.370
