### ISSUE TITLE
Version that works with D365 9.0 online?

### ISSUE THREAD

**Issue by ArtKarp** [scottdurow/SparkleXrm#247]
The readme says "Compatible with CRM2011, CRM2013 and CRM2015. The 0.x solution is a CRM2011 managed solution that can also be imported into CRM2013. The 7.x solution is CRM2015 managed solution."

I haven't been able to locate any other version. Is there a version that works with VS 2017 and Dynamics 365 Online (v9.0)?

Thanks

**Comment by scottdurow** [comment]
Hi - thanks for this - I need to upgrade that readme! The latest version is compatible with VS2017 and Dynamics 365 v9. The latest solution zip is in Nuget.

**Comment by ArtKarp** [comment]
Great to know.  I will check it out. 
Thanks

**Comment by lheng18** [comment]
@scottdurow Does SKPL support the latest SDK. from the log I saw it uses Dynamics SDK 9.0.0.7 even with the latest SPKL?
