### ISSUE TITLE
SPKL: Option for AutoDetect on Web Resources

### ISSUE THREAD

**Issue by mattp65** [scottdurow/SparkleXrm#248]
It would be nice to have an AutoDetect option for Web Resources. This would eliminate the need to maintain spkl.json every time an entry is added/removed to the directory tree and would use the folder hierarchy to drive the registration (including removing files no longer present in the directory tree). Deletes would probably need to handle possible dependency issues.

This could allow spkl.json to be something like this:
```
  "webresources": [
    {
      "profile": "default,debug",
      "root": "Webresources/",
      "solution": "MySolution",
      "autodetect": "true",
      "deleteaction": "remove|delete|nothing",
      "prefix": "mypfx"
    }
  ]
```

**Comment by mattp65** [comment]
Added a Pull request with this change implemented.

**Comment by scottdurow** [comment]
This is released as https://www.nuget.org/packages/spkl/1.0.370
