### ISSUE TITLE
Release notes for spkl task runner

### ISSUE THREAD

**Issue by devkeydet** [scottdurow/SparkleXrm#257]
I don't see any on the wiki here or at https://www.nuget.org/packages/spkl/.  Are they located somewhere?  If not, would you consider publishing some?

**Comment by scottdurow** [comment]
Thanks for the nudge! 👍  I need to get better at keeping the release notes up to date.

Here are the notes for the latest release - https://github.com/scottdurow/SparkleXrm/releases/tag/spkl-v1.0.226

There is a project board that tracks issues and enhancements - https://github.com/scottdurow/SparkleXrm/projects/1
