### ISSUE TITLE
Register Message Step for Global Custom Action using CrmPluginRegistrationAttribute

### ISSUE THREAD

**Issue by pahansen** [scottdurow/SparkleXrm#267]
Is it possible to register a message step for a global custom action just like Update, Create, etc. using spkl? It seems like an entity logical name is always required when registering a step. However, when using global custom action I don't have any entity available that I could use

**Comment by scottdurow** [comment]
Hi - you can simply use “none” as the logical name and t will register the step on all entities.

**Comment by pahansen** [comment]
Perfect - couldn't be easier! Thanks for the quick help
