### ISSUE TITLE
AutoDetect trying to delete existing Web Resource - SPKL Beta

### ISSUE THREAD

**Issue by mattp65** [scottdurow/SparkleXrm#276]
Logic I added tries to delete a Web Resource that is present in the directory if the Case on the file name has changed. Need to modify the following line in the DeployDirectory method:

WebResource webResourceListItem = curWebResources.FirstOrDefault(wr => wr.Name == relativePathFileName.Replace("\\", "/"));

to the following:
WebResource webResourceListItem = curWebResources.FirstOrDefault(wr => wr.Name.ToLower() == relativePathFileName.ToLower().Replace("\\", "/"));

**Comment by scottdurow** [comment]
Good spot - Will you do a PR and add a unit test for that issue?

**Comment by mattp65** [comment]
Yes, doing some more testing.

**Comment by scottdurow** [comment]
Included in https://www.nuget.org/packages/spkl/1.0.233-beta

**Comment by scottdurow** [comment]
This is released as https://www.nuget.org/packages/spkl/1.0.370
