### ISSUE TITLE
Add to spkl.json from the solution

### ISSUE THREAD

**Issue by FixRM** [scottdurow/SparkleXrm#292]
Hello @scottdevelop1,

Can you please explain this example: https://github.com/scottdurow/SparkleXrm/wiki/spkl#adding-to-a-solution? I'm doing reverse engineering of third party solution and looking for a way to generate `webresources/files` config section based on project content. I used `downloadwebresources.bat` to have all the files locally, but there are a lot of unwanted files there so It's a pain to delete them two times.

p.s. You mentioned in #166 that glob is supported for web resources. Can you provide an example please?

**Comment by scottdurow** [comment]
Hi - you can use get-webresources to create a spkl.json file to match your local files to currently deployed webresources - is this what you mean?

As far as glob support - where you specify a file path you can use glob wildcards - e.g. \bin\**\TestPlugin.dll will search for the plugin under either the Debug or Release folder.

**Comment by FixRM** [comment]
Hello @scottdevelop1,

As far as I understand, `get-webresources` generate spkl.json from CRM webresouces. `download -webresources` do the same plus it get resources themselves and add them to VS solution. Is there any way to generate spkl.json based on VS solution, but not from CRM solution?

Why I am asking? Web resources are not only about the code. There are a lot of entity icons and I don't want them to be a part of VS solution as it takes dozens of minutes to deploy them.

**Comment by FixRM** [comment]
Anyway, thanks. I already deleted all unnecessary resources manually.
