### ISSUE TITLE
Plug-In Deployer silently failing on some classes with PostImage in CrmPluginRegistration

### ISSUE THREAD

**Issue by GM-GEO** [scottdurow/SparkleXrm#304]
Using the Plug-in Deployer tool from Visual Studio will begin to correctly register plugins, but will consistently fail (in our solution) when attempting to register the PostImage. When we comment out the image attributes in the CrmPluginRegistration, the tool correctly registers but then fails on another SetState plugin with a PostImage. The confusing thing here is that we only have a handful of plugins behaving this way, the majority of the plugins seem to consistently deploy.

The entirety of the logging information reported back to VS2017 is the following (the tool unlocks the UI but doesn't print anything beyond the last INFO message)

    INFO | 2/21/2019 10:33:20 AM: Connected to: https://custom.crm3.dynamics.com | Version: 9.1.0.2618
    INFO | 2/21/2019 10:33:20 AM: Retrieved solutions
    INFO | 2/21/2019 10:33:22 AM: Retrieved assembly: 4be3fbee-572a-e911-a973-000d3aff2e34
    INFO | 2/21/2019 10:33:23 AM: Updating Plugin 'custom.Plugins' from '...\bin\Release\custom.Plugins.dll'
    INFO | 2/21/2019 10:33:23 AM: Updating Type 'custom.Plugins.PostApprovalCreateIncrementApprovalCount'
    INFO | 2/21/2019 10:33:23 AM: Updating Step 'PostApprovalCreateIncrementApprovalCount'
    INFO | 2/21/2019 10:33:24 AM: Updating Type 'custom.Plugins.PostApprovalDeleteChangeApprovalCount'
    INFO | 2/21/2019 10:33:24 AM: Updating Step 'PostApprovalDeleteChangeApprovalCount'
    INFO | 2/21/2019 10:33:24 AM: Updating Image 'PreImage'
    INFO | 2/21/2019 10:33:25 AM: Updating Type 'custom.Plugins.PostApprovalSetStateDecrementApprovalCount'
    INFO | 2/21/2019 10:33:25 AM: Updating Step 'PostApprovalSetStateDecrementApprovalCount'
    INFO | 2/21/2019 10:33:26 AM: Registering Image 'PostImage'

And the CrmPluginRegistration on the SetState plugin is:

`
    [CrmPluginRegistration("SetState", 
    "custom_approval", StageEnum.PostOperation, ExecutionModeEnum.Asynchronous,
    "","PostApprovalSetStateDecrementApprovalCount", 10, 
    IsolationModeEnum.Sandbox 
    ,Image1Type = ImageTypeEnum.PostImage
    ,Image1Name = "PostImage"
    ,Image1Attributes = "regardingobjectid"
    ,Description = "Post-Operation of Approval SetState"
    ,Id = "8b96e861-592a-e911-a980-000d3aff2e31" 
    )]
`

We require info in a log file with exception details if this seems like something we can fix locally, otherwise we're not sure what is causing this plugin to fail compared to the other plugins we have. The deploy-plugins.bat file does not suffer from this issue, however the drawback there is we cannot specify the solution we want to target for deploying the plugins.

**Comment by jklosinski** [comment]
Possibly added after this issue was opened, but the spkl.json file supports specifying the solution name:

```json
{
  "plugins": [
    {
      "solution": "Test",
      "assemblypath": "bin\\Debug"
    }
  ]
}
```
