### ISSUE TITLE
Spkl not including CanvasApp embedding changes while packing, unpacking CRM solution.

### ISSUE THREAD

**Issue by jaimalleshk** [scottdurow/SparkleXrm#333]
Spkl not including CanvasApp embedding changes while packing, unpacking CRM solution.

While troubleshooting I found that the solution packager works well if we unpack/pack directly using it. But Spkl is not giving proper instructions to solution packager which in turn is causing solution packager to ignore canvas app (power apps) form embedding changes. I have also attached the solution comparison which shows that spkl package is missing canvasapp folder and respective changes.
![spkl canvas app packaging issue](https://user-images.githubusercontent.com/3666316/63452212-57e7bc80-c40b-11e9-895f-7c69decfbcab.png)

**Comment by scottdurow** [comment]
Hi,
This is likely due to the version of the solution packager that spkl is using. You should be able to update the nuget version of the Core Tools on the project that contains the spkl nuget package reference.

**Comment by jaimalleshk** [comment]
Thank you Scott. This helped :). I updated the core tools to 9.0.3.4 and now the packaging and unpacking from spkl shows canvas app control changes.
