### ISSUE TITLE
Ability to run bat in silent mode using defaults

### ISSUE THREAD

**Issue by joserito** [scottdurow/SparkleXrm#335]
Hello,
Is there a way to run spkl bat files without being prompted for parameters and using all defaults (e.g. default connection, etc.)?
The scenario I have is packing solution as part of building solution in VS by calling the pack command in pre-build event.
Any guidance on this subject would be very appreciated.

**Comment by scottdurow** [comment]
Yes - you can call spkl with a connection string - see https://www.youtube.com/watch?v=kfTYf2Sm_Ew&feature=youtu.be

**Comment by joserito** [comment]
Thanks so much Scott!
