### ISSUE TITLE
How to get around the 'Block Legacy Authentication' setting

### ISSUE THREAD

**Issue by Edwin-VC** [scottdurow/SparkleXrm#369]
I am a heavy user of the XRMToolbox and @scottdurow many thank for your efforts inside and outside the toolbox 👍.

One of my customers has decided they need to enable 'Block Legacy Authentication': https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/block-legacy-authentication

This does introduce a couple of issues for the CRM Team using the XRMToolbox and SPKL to name one. Within the Toolbox we can now connect using an App Registration in AAD. But I cannot find such an option in the SPKL console. What would be an option to keep working with SPKL in this situation?

**Comment by scottdurow** [comment]
Currently - you would have to connect using a connection string - we are currently working on a command line login that will use Xrm Tooling.

**Comment by scottdurow** [comment]
This is now fixed in the latest beta release - can you confirm that this works for you please?
