### ISSUE TITLE
Not able to connect to Crm 9.1 getting Authentication failure Error

### ISSUE THREAD

**Issue by vivekkk4** [scottdurow/SparkleXrm#375]
We are getting this error as spkl is trying to connect using organization service but in microsoft last month went for upgrade all the crm instance and not allowing connection to crm suign orginaztion service instead we need to use crm proxy service.

Error Message "Exception Occured--An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail."

**Comment by scottdurow** [comment]
Could you try using https://www.nuget.org/packages/spkl/1.0.394-beta

**Comment by vivekkk4** [comment]
thanks Scott, got fixed by this release.
