### ISSUE TITLE
Support for DeliverImmediatePromote as a plugin message is missing in spkl

### ISSUE THREAD

**Issue by karankkrj2020** [scottdurow/SparkleXrm#408]
Hi @scottdurow 

Microsoft Dynamics Support DeliverImmediatePromote message as part of plugin registration but the same seem to be missing as part of spkl. The result is we have to re-add the steps with DeliverImmediatePromote manually everytime the deploy-plugin command is executed as part of spkl. Please consider adding the support for the same.

![DeliverImmediatePromoto](https://user-images.githubusercontent.com/72430817/107495629-a0abac00-6b90-11eb-959c-a727d68c12f3.PNG)

Thanks,
Karan

**Comment by scottdurow** [comment]
Hi @karankkrj2020 - thank you for this. Please see #409
