### ISSUE TITLE
Unable to Registered a plugin on DeliverImmediatePromote message for email entity

### ISSUE THREAD

**Issue by Yogesh-Kardak** [scottdurow/SparkleXrm#409]
Hello Team,

Current spkl runner doesn't support "DeliverImmediatePromote" message, but it supports "DeliverPromote".

So now we have to create  "DeliverImmediatePromote" message step manually using the plugin registration tool.

Is there any way we can register a plugin on DeliverImmediatePromote message?

**Comment by scottdurow** [comment]
Hi @Yogesh-Kardak - thanks for this. As a workaround, you should be able to specify the message name as a string using the alternative constructor.

**Comment by Yogesh-Kardak** [comment]
@scottdurow  - Thank You So Much .
