### ISSUE TITLE
[question]I'm trying to implement SPKL, the deployment to Prod environment of plugins is with or without solution?

### ISSUE THREAD

**Issue by JuanFDiazGomez** [scottdurow/SparkleXrm#411]
Hi there, I'm new using SPKL it confuses me a bit.

The tool is prepared to run publish and create the assembly and plugins with their steps. I understand this as a development environment approach. Then in my mind i thought that this would create a solution  and it would add those elements to the solution and then import that solution to, test,prod etc

But after playing a bit with this i don't see any solution being created automatically so, i guess that the approach here is as the same we do with dev publishing the assembly, doing the same to the other environments without having that in a solution first?

So in production the assembly won't be on any specific solution.

Is that right?

Thanks!,
Juan

**Comment by scottdurow** [comment]
You would only use spkl to deploy your plugin assembly and steps to a development environment.
Once it's there, you would unpack your solution into Source Control and then use that as the target for downstream deployments.

So the steps would be:
1. Developer creates plugin and adds [CrmPluginRegistration steps](https://github.com/scottdurow/SparkleXrm/wiki/spkl#how)
2. Developer deploys to development environment using spkl - Assembly and steps are automatically added to a solution if you specify the solution in your spkl.json
3. Developer [unpacks Solution](https://github.com/scottdurow/SparkleXrm/wiki/spkl#solution-packager) to get all the solution as xml metadata
4. Developer commits changes (metadata and Plugin c#) and creates Pull Request
5. Pull Request Merged - Build Pipeline builds then builds plugin c#, adds the pluign assembly to the package folder - then packs the solution into a solution.zip so it can be imported/deployed etc.

**Comment by JuanFDiazGomez** [comment]
Hi Scott!

Thanks so much for your help. Now i understand the main advantage of using
SPKL. Having directly the assemblies and step stored in a solution and the
simplicity of publishing those plugins.

I have one question then and i would like to know your opinion.

All the deployment we do to other environments as Test/Prod we are
importing the solution as managed for configuration and customization.

If i isolate plugins in a unique solution for them, would you advice to
move them managed or unmanaged?

Thanks,
Juan

**Comment by scottdurow** [comment]
Hi @JuanFDiazGomez  - if you have managed solution in Test/Prod then I would recommend you deploy your plugins as Managed as well - ideally in the same solution as the other components.

**Comment by JuanFDiazGomez** [comment]
Ohh alright. I had on my mind that using SPKL would change the process i
have implemented already...

We all are working in one development environment and with a developer
solution for each one and then merging that into the master solution.

I think that even using SPKL won't help me with the issue that the assembly
it's the same one for everyone, so if the assembly is updated by the
developer B, when developer A is starting the pipeline to export his
solution and merge into the master solution will contain the assembly with
the changes of developer B who hasn't been reviewed in a pull request...

Thanks,
Juan

**Comment by scottdurow** [comment]
That's a common issue where you have parallel teams. My guidance for this kind of work is to have separate dataverse environments for each parallel branch - then you can merge code/metadata between branches and deploy to the respective environments.

If you don't have any metadata changes between the parallel branches - then you can always just use the spkl plugin attributes to deploy other people's work to your local environment after you have merged their code.
