### ISSUE TITLE
Plugins: Delete AsyncOperation if StatusCode = Succesful

### ISSUE THREAD

**Issue by vandyckth** [scottdurow/SparkleXrm#413]
When adding an async PostOperation-step with the CrmPluginRegistrationAttribute.cs, there is a property 'DeleteAsyncOperaton' (type, by the way, should be DeleteAsyncOperation) of type 'bool?'. When adding this property to my class decorator, I get this error:
![image](https://user-images.githubusercontent.com/26608333/112753580-55324d80-8fd8-11eb-900f-9f24058c4cd1.png)

Fixed this issue by replacing type 'bool?' with type 'bool' in CrmPluginRegistrationAttribute.cs.

**Comment by scottdurow** [comment]
There was a long-standing typo in that attribute which was fixed recently - you'll need to update your CrmPluginRegistrationAttribute to https://github.com/scottdurow/SparkleXrm/blob/203181ae0d27e59390b0707807cc31a3003b732c/spkl/SparkleXrm.Tasks/CrmPluginRegistrationAttribute.cs#L101

Also - make sure you have the latest beta installed
