### ISSUE TITLE
Plugins: Filtering attributes and Image attributes

### ISSUE THREAD

**Issue by vandyckth** [scottdurow/SparkleXrm#414]
Filtering attributes and Image attributes can 't contain spaces when adding multiple attributes when using the CrmPluginRegistration-decorator. Please fix this by removing all spaces from those strings when performing (by example) the deploy-plugins.bat.

**Comment by scottdurow** [comment]
Fixed in https://www.nuget.org/packages/spkl/1.0.633-beta
