### ISSUE TITLE
Should my solution packager project build?

### ISSUE THREAD

**Issue by bwmodular** [scottdurow/SparkleXrm#425]
Hi there,
I've got my unpack and pack tasks running nicely, no errors, but when I actually add the unpacked solution folder and its contents into my project, I end up with lots of compilation errors, most commonly:
_Parameter of type 'System.Object' not supported for Attributes._	
which appears for the xaml workflow defintions.
and
_Unknown build error, ''clr-namespace:Microsoft.Crm.Workflow.ClientActivities;assembly=Microsoft.Crm.Workflow, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' mapping URI is not valid._
which appears in xaml formula defintions

I didn't have the same issue when using the software developer toolkit to pack/unpack, so I know that it should be possible to compile such a project (it's pretty much only xml and xaml, right?) and I've compared references between the two projects and can't find anything missing.

Any ideas?

Thanks

**Comment by scottdurow** [comment]
Hi @bwmodular  - I suspect that this is because Visual Studio is considering the xaml as a source file. I tend not to include the package folder in the project - but use Visual Studio's folder view instead (similar to VSCode)

**Comment by bwmodular** [comment]
Hi @scottdurow, probably a stupid question but how do you get the unpacked solution under source control if you don't include it in the project.
I've just excluded it from the build using the Configuration Manager in VS, so I've solved my problem, but I thought one of the main points of doing this was to get your customisations under source control so you can track changes.

**Comment by scottdurow** [comment]
Not a stupid question! Source control isn't directly linked to the project items in git - you can add items that are not part of the project files.

**Comment by bwmodular** [comment]
Thanks Scott, as ever. I'll close this issue.
