### ISSUE TITLE
QuoteLineEditor : Update on Lookup field does not work

### ISSUE THREAD

**Issue by wlsoh2003** [scottdurow/SparkleXrm#44]
Lookup editor Property change event does not work.
The "IsValueChanged" method of XrmLookUpEditor.cs  always returns false , which does not call the property change event and thus the entityState remains Unchanged and the changes are not saved.

**Comment by scottdurow** [comment]
Fixed in #49

**Comment by BobHatcher** [comment]
Thank you for the updated package - I appreciate it!

With this version the `SearchCommand` is working - I get matches to my search but when I make a selection, the Lookup is set to null.

![image](https://cloud.githubusercontent.com/assets/12090526/7947297/3fc652d6-094a-11e5-8ec4-610cf7e08c1c.png)

However, the indicator in the leftmost column updates to show the row is dirty. When I save, it tells me `customerid` can't be blank.

![image](https://cloud.githubusercontent.com/assets/12090526/7947320/750f6d7e-094a-11e5-9a30-7279f87e16cc.png)

This now occurs on all Lookups, not just ones against multiple entity types. I can still change non-Lookup values without an issue.

This is still on a standalone page I'm popping open with a Ribbon button, if that matters.

Thank you again for you help!
