### ISSUE TITLE
How to Start!!

### ISSUE THREAD

**Issue by shpedro** [scottdurow/SparkleXrm#45]
Hello,
First of all this is one of the greatest products out there...

We are developing a custom Dashboard (Dashboard using a single webresource),
and we need to add grids and graphics with the same look and feel of CRM 2013.

We download your solution, the examples are amazing. The thing is.... were can we start building our one html grid?
we are lost
Can you please help us getting started?

**Comment by scottdurow** [comment]
Thanks for the encouragement. I quick start on how to create a simple grid is work in progress - in the meantime, the best place to look at is the Quote Editor Example.

**Comment by scottdurow** [comment]
Check out the tutorial videos! That should be enough to get you started!
http://www.sparklexrm.com/s/tutorials.html
