### ISSUE TITLE
spkl.exe plugins need Release with starting uppercase

### ISSUE THREAD

**Issue by rappen** [scottdurow/SparkleXrm#472]
Folders don't usually require cases letters when comparing folders.
But in spkl it does.

Calling:
`spkl.exe plugins <source> <connectionstring> /p:Release`

It needs the R  to be uppercase.
For `/p:debug` it needs to start with a lowercase.
Tiny inconsistent...
Since when I test, in the explorer I see that both start with uppercase, but it needs a `R` and `d`. Weird...

It's not the `<soucepath>` I'm talking about, it's the `/p:`.

I hope this awesome tool can improve to compare folders without case. Please? 😊

**Comment by rappen** [comment]
Note: for another project - I need to use `r`.
Still has `R` in the folder name.

**Comment by scottdurow** [comment]
Hi @rappen,
The `/p` switch refers to the profile to use in the `spkl.json`.

By default it is set to `"profile": "default,debug"` which means you can pass `'/p:debug` or not supply `/p` at all to use the default profile.

Could you check if you have a `"profile": "release"` section in your `spkl.json` - or if it is set to `"profile": "Release"`

Thanks!

**Comment by rappen** [comment]
Of darn... you are correct, as always....
It is very case sensitive - but not in the folder, but in the spkl.json.

Case closed.
