### ISSUE TITLE
SparkleXrmUI.js - Syntax Error

### ISSUE THREAD

**Issue by BobHatcher** [scottdurow/SparkleXrm#52]
Scott, the issue I had and asked about on Twitter I successfully traced to a syntax error in the following:

```javascript
                validationIndicator.position({
                                            my: 'left bottom',
                                            at: 'left top',
                                            collision: 'fit fit',
                                            of: activeCellNode
                                        })
                                        .show({
                                        effect: 'blind'
                                        })
                                        .delay( 500000 )
                                        .hide({
                                            effect: 'fade',
                                            duration: 'slow', 
                                        },
                                            function() {
                                                $( this ).remove();
                                                
                                            });
                                        ;
```

I'm still learning this so please forgive me that I am not precisely sure where the root of this error is.

There is a comma after ```duration: 'slow'``` which causes a parsing error. I simply took the comma out by opening your managed package (using 0.2.0 because I am on 2011) and editing the SparkleXrmUI.js at line 2791.

I believe this is still in there, since I found the same issue in a recent clone - /DebugWeb/WebResources/sparkle_/js/SparkleXrmUI.js
at line 208.

When rendering in a standalone window, this caused the whole SparkleXrm object to be undefined. Not sure why this works when running inside a standard entity window.

Thank you for a great toolset. I'm still coming up to speed on it but I'm already using it to great effect for the 2nd time.

**Comment by scottdurow** [comment]
Thanks Bob.
The evil comma of doom! What browser does this happen in? IE8?

**Comment by BobHatcher** [comment]
IE 11.0.18; I didn't try it in any other browsers.

**Comment by scottdurow** [comment]
Interesting - which DOCTYPE does your HTMLwebresource use?

**Comment by BobHatcher** [comment]
Should have mentioned it's compatibility mode, so I believe that means 5.

I was using your GridEdit.htm with almost no modification so there was no <!DOCTYPE html> in there (my oversight).

**Comment by scottdurow** [comment]
Does adding <!DOCTYPE html> fix it? Trailing commas are allowed in recent ECMA standards  - but I think I'll remove it for safety.

Thanks!

**Comment by BobHatcher** [comment]
I cracked open the managed package and manually deleted the comma, so I don't know if that's the magic bullet.

The DOCTYPE tag seems to be necessary to get the columns to render in a standalone window, so thay may be a good tweak as well unless it'll break something I'm not thinking of.

**Comment by scottdurow** [comment]
I'd go with <!DOCTYPE html>

**Comment by BobHatcher** [comment]
Yep! New hotness is that the standalone version doesn't seem to be rendering dates. Set 'em up, knock 'em down...

**Comment by scottdurow** [comment]
In a form field or grid? When you say not rendering - does it throw an error?
I use date pickers in forms and grids quite a bit and I've not had any trouble.

**Comment by BobHatcher** [comment]
Works fine if the grid is present as a standard Web Resource on a form.

When rendered as standalone (point browser to https://myserver.com/CRMTest/WebResources/ics_/html/GridEdit.htm) they are NaN.

On a Form:
![image](https://cloud.githubusercontent.com/assets/12090526/7541196/44f46752-f581-11e4-8031-3f2f3d3bbf74.png)

Standalone:
![image](https://cloud.githubusercontent.com/assets/12090526/7541185/317f57e0-f581-11e4-809b-276896e840be.png)

**Comment by BobHatcher** [comment]
With. Still IE 11 in compatibility mode.

**Comment by scottdurow** [comment]
Are you using XrmDateEditor.BindColumn on this column? 
Would you be able to send me a repro solution?

**Comment by BobHatcher** [comment]
I sent you a Twitter DM with a link.

Yep, using the DateEditor and Bind Column.

```C#
XrmDateEditor.BindColumn(
     GridDataViewBinder.AddColumn(columns, "Est Close", 200, "estimatedclosedate"),true);
```

Thank you very much for your help on this. I owe you a beer at the next conference!

**Comment by scottdurow** [comment]
Got it! Thanks.

**Comment by scottdurow** [comment]
Try moving the meta tags in GridEdit.htm so that they are inside the <head>
```
<!DOCTYPE html>
<html lang="en">
    <head>    
    <title>Opportunity Line Item Editor</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
```
This is as per snippet - SparkleXrm/Snippets/Visual Web Developer/My HTML Snippets/sparkle-view-page.snippet

**Comment by BobHatcher** [comment]
So in the end it worked if I set IE = 9, not Edge.

Thanks again. We're past beer, now I think I owe you dinner!

**Comment by scottdurow** [comment]
My pleasure! Glad you've got it working!
