### ISSUE TITLE
Grid Editor - Displaying Aliased Values On Lookup Fields

### ISSUE THREAD

**Issue by BobHatcher** [scottdurow/SparkleXrm#53]
I am using Grid Editor to display an Opportunity Product. I have a Lookup to the Existing Product. This follows the pattern as Scott's sample for the Quote editor.

When I use the Lookup, I want it to display the `productnumber` field rather than `name`. I can edit this when the user conducts a search by editing the `SearchCommand`.

But when I load the Editor again, I get the name attribute again.

In the constructor for the OpportunitylineItemEditorViewModel, there is a Fetch, to which I added:
```xml
...
<link-entity name='product' from='productid' to='productid' visible='false' link-type='outer' alias='ep'>
     <attribute name='productnumber' />
</link-entity>
...
```

Note the alias name `ep` to represent the existing product.

So when I try to use this in the `init`, I can't get it to recognize the `productnumber` name.

```C#
            XrmLookupEditor.BindColumn(
                GridDataViewBinder.AddColumn(columns, "Existing Product", 200, "productid"),
                vm.ProductSearchCommand, "productid", "ep.productnumber", "");
```

The dot syntax (`ep.`) is the way it's done in JavaScript in my experience, so I'm using that.

I also tried updating the ScriptName variables in both the Model (OpportunityProduct.cs) and Observable ViewModel (ObservableOpportunityProduct.cs), e.g.,

```C#
        [ScriptName("ep.productnumber")]
        public Observable<string> ProductNumber = Knockout.Observable<string>();
```

Is this supported? If so, I'd appreciate some feedback on where I'm going wrong. Thank you!

**Comment by scottdurow** [comment]
The standard formatter for the XrmLookupEditor always uses the name of the entity reference to display - if you want to change this you'll need to change the formatter on the column after you've called BindColumn. Let me know if you need an example.

**Comment by BobHatcher** [comment]
An example would be great. Thank you!

**Comment by scottdurow** [comment]
Something like:
```c#
Column productIdColumn = XrmLookupEditor.BindColumn(
GridDataViewBinder.AddColumn(columns, "Existing Product", 200, "productid"),
vm.ProductSearchCommand, "productid", "ep.productnumber", "");

productIdColumn.Formatter = delegate(int row, int cell, object value, Column columnDef, object dataContext)
 {
    EntityReference entityRef = (EntityReference)value;
    Entity record = (Entity)dataContext;
    return "<a href='#' class='sparkle-lookup-link' entityid='" + entityRef.Id +"' typename='" + entityRef.LogicalName + "'>" + XmlHelper.Encode(record.GetAttributeValueString("productnumber")) +"</a>";
};
```

**Comment by BobHatcher** [comment]
Thank you. I dropped this in but I am getting an error that it can't find the id of a null reference.

The implication is that the values being passed into the delegate are null, which they are at least in the F12 debugger. I'm new to the method you've used for anonymous delegates - I see that this calls `ColumnFormatter` in `GridDataViewBinder` but I'm not sure where the arguments to the method are coming from - I don't see them inherited from `ViewBase`.

**Comment by scottdurow** [comment]
ColumnFormatter is just the delegate method signature that you must use:
    public static string ColumnFormatter(int row, int cell, object value, Column columnDef, object dataContext)

Perhaps you have add new rows enabled - in which case you'll get a null value passed in for those new rows - just test for null and return an empty string from the formatter.

**Comment by BobHatcher** [comment]
But it shouldn't be null. I'm loading existing records into the grid and if I comment out the return the row renders with the Lookup column blank.

**Comment by scottdurow** [comment]
What happens if you use:
```javascript
productIdColumn.Formatter = delegate(int row, int cell, object value, Column columnDef, object dataContext)
 {
    if (value==null) return "";
    EntityReference entityRef = (EntityReference)value;
    Entity record = (Entity)dataContext;
    return "<a href='#' class='sparkle-lookup-link' entityid='" + entityRef.Id +"' typename='" + entityRef.LogicalName + "'>" + XmlHelper.Encode(record.GetAttributeValueString("productnumber")) +"</a>";
};
```

**Comment by BobHatcher** [comment]
Thanks - I get
![image](https://cloud.githubusercontent.com/assets/12090526/7731386/0ee404c6-feee-11e4-8f05-1682e268673a.png)

I think for this one I'm just going to rejigger the source data for now.

Thank you for your help!
