### ISSUE TITLE
Support for VS2013 and beyond

### ISSUE THREAD

**Issue by dipple** [scottdurow/SparkleXrm#54]
Scott,
Any news on the possible support of VS2013 or later?  I would really like to do more with SparkleXRM but I would need to be able to develop with VS2013.

**Comment by scottdurow** [comment]
Provided you can get VS2013 working with the developer toolkit it should be fine - see https://community.dynamics.com/crm/b/tsgrdcrmblog/archive/2014/08/23/microsoft-dynamics-crm-2013-toolkit-with-visual-studio-2013
________________________________
