### ISSUE TITLE
Sparkle Subgrid - OnChange event for 1 field only 

### ISSUE THREAD

**Issue by dos757** [scottdurow/SparkleXrm#55]
Hello guys, 

I'm contacting you because i'm trying to change the value of the field "A" only if i change the value of the field "B". Currently and via the "PropertyChanged " method,  when i change every field of a row, the field "A" is automatically modified. 

Thanks for your help.

Jean-Michel

**Comment by scottdurow** [comment]
I don't quite follow. Could you post some code to demonstrate your issue?

**Comment by scottdurow** [comment]
Do you still have this issue - or can we close it?
