### ISSUE TITLE
Changing Lookup Values on Multi-Entity Lookups

### ISSUE THREAD

**Issue by BobHatcher** [scottdurow/SparkleXrm#56]
I have a grid editor against Opportunity that has a lookup to an Account. That Lookup works fine.

This grid editor also has two other lookups to customerid (could be Account or Contact) as well as ownerid (could be User or Team). These don't work; when they are changed, the SearchCommand runs fine, but when I choose a different value the system does not recognize it has changed by placing the little icon on the left side of the row.

Seeing as the two with variable types don't work and the one with a constant type does, I'm assuming this has something to do with the typecodes.

I notice that the BindColumn on LookupEditor has a  `typeCodeAttribute` that in the Quote example is passed as an empty string. So I tried entering "systemuser" as well as "8" (since this parameter expects a String) but based on my investigation so far it seems this value is only used to select an icon to present to the user. e.g,

```C#
            XrmLookupEditor.BindColumn(
             GridDataViewBinder.AddColumn(columns, "Owner", 150, "ownerid"),
             vm.OwnerSearchCommand, "ownerid", "fullname", "systemuser");
```

Adding the `systemuser` parameter actually causes a JavaScript error when it runs the code that appears in C# in XrmLookupEditor.cs at line 138.
`typeCodeName = fetchResult.Entities[i].GetAttributeValue(editorOptions.typeCodeAttribute).ToString();`

It also appears that the SearchCommand populates the CRM type code properly based on the type you search for. If I put a breakpoint at the 2nd to last line at EntityCollection I see each returned value has its typecode properly set to "systemuser".

```C#
        public void OwnerSearchCommand(string term, Action<EntityCollection> callback)
        {
            string fetchXml = @" <fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                                  <entity name='systemuser'>
                                    <attribute name='systemuserid' />
                                    <attribute name='fullname' />
                                    <order attribute='fullname' descending='false' />
                                    <filter type='and'>
                                      <condition attribute='fullname' operator='like' value='%{0}%' />
                                    </filter>
                                  </entity>
                                </fetch>";
            fetchXml = string.Format(fetchXml, XmlHelper.Encode(term));
            OrganizationServiceProxy.BeginRetrieveMultiple(fetchXml, delegate(object result)
            {
                EntityCollection fetchResult = OrganizationServiceProxy.EndRetrieveMultiple(result, typeof(Entity));
                callback(fetchResult);
            });
        }
```

So, am I barking up the wrong tree here with the typecodes, and if so am I doing anything wrong?

**Comment by scottdurow** [comment]
The ```typeCodeattribute``` parameter should be the name of the field that stores the entitytypename. So it would be a field on the Entity that holds 'systemuser'. You can see an example of this in the timesheet sample - https://github.com/scottdurow/SparkleXrm/blob/master/SparkleXrmSource/Client/TimeSheet/View/TimeSheetView.cs#L99

In this case, the activityTypeCode is actually an attribute returned from the fetchxml - but you could populate this manually based on your search results when you combine the queries for multiple entity types into a single SearchCommand result set.

**Comment by BobHatcher** [comment]
OK, thank you, from the example you provided and further investigation the logical name/type codes don't seem to be an issue.

I traced a few samples and I've found that in the case of these two Lookups, the `raisePropertyChanged` does not appear to fire. When I change other fields, even Lookup fields, I see `RaiseOnChange` and `RaisePropertyChanged` firing when I run an F12 trace.

Is there something special I I need to do to register the event?
```C#
CustomerId.Subscribe(delegate(EntityReference value)
            {
                OnValueChange("customerid", value);
            });
```

Second question and sorry if this is stupid and/or obvious: the arguments for the Lookup BindColumn, i.e.,
```C#
            XrmLookupEditor.BindColumn(
             GridDataViewBinder.AddColumn(columns, "Owner", 150, "ownerid"),
             vm.OwnerSearchCommand, "ownerid", "fullname", "systemuser");
```

Both the `id` fields refer to the field on the primary entity, right? In my case I am dealing with Opportunities, and the Lookup field is `customerid`. But on Account, its own ID in its own table is `accountid`. So if I am on Opportunity and want to search Accounts should *both* ID fields read `customerid`?

**Comment by scottdurow** [comment]
This sounds similar to #49 - What version are you using of the SparkleXRM Solution?

**Comment by scottdurow** [comment]
Re you question about the XrmLookupEditor - the idAttribute parameter of BindColumn is the attribute to use to set the id of the EntityReference. You can set it to 'id' if you are using an Entity that is returned from a RetrieveMultiple. 
I've added a sample of this for you - https://github.com/scottdurow/SparkleXrm/commit/5eea0900c7f0cddfe1d531d1a7a82338755b6f45

Hope this helps!

**Comment by BobHatcher** [comment]
You're right, it does sound like that error. I am using 0.2.0 since I understood that to be the only release available for 2011. 

Thank you, as always, for your time and willingness to help little 'ol me work this out.

**Comment by scottdurow** [comment]
Right - you're using CRM2011. I'll publish a release for CRM2011 based on the current 2015 version.

**Comment by BobHatcher** [comment]
Thank you, that would be outstanding.

**Comment by scottdurow** [comment]
Here you are: https://github.com/scottdurow/SparkleXrm/commit/1d0395276d5e3f5fb43426ae484388b186d67e07

Let me know how you get on!

**Comment by scottdurow** [comment]
If you still have issues I'm sure I can create a sample if you can provide more details of your scenario.

**Comment by BobHatcher** [comment]
I took your Quote Detail example and updated it to point to Opportunities. I placed it on a straight-up HTML Web Resource that pops open with a Ribbon button - so it doesn't live on a standard CRM form. This is CRM 2011 on premise UR14.

I have an `Opportunity.cs` that declares the variable.

```C#
        [ScriptName("customerid")]
        public EntityReference CustomerId;
```

In the constructor for the Opportunity I set:
```C#
            this._metaData["customerid"] = AttributeTypes.EntityReference;
```

There is nothing in the Event Handlers since there's no calcs or validation I need.

In `ObservableOpportunity.cs` I have a declaration:
```C#
        [ScriptName("customerid")]
        public Observable<EntityReference> CustomerId = Knockout.Observable<EntityReference>();
```

and in the constructor I subscribe:
```C#
 CustomerId.Subscribe(delegate(EntityReference value)
            {
                OnValueChange("customerid", value);
            });
```

In SetValue() I have
```C#
            this.CustomerId.SetValue(InnerOpportunity.CustomerId);
```

and in Commit() I have
```C#
            InnerOpportunity.CustomerId = Knockout.UnwrapObservable<EntityReference>(CustomerId);
```

I then bind the column in the View
```C#
            XrmLookupEditor.BindColumn(
             GridDataViewBinder.AddColumn(columns, "Customer", 150, "customerid"),
             vm.CustomerSearchCommand, "customerid", "name", "");
```

My SearchCommand:
```C#
        public void CustomerSearchCommand(string term, Action<EntityCollection> callback)
        {
            string fetchXml = @" <fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                                  <entity name='account'>
                                    <attribute name='accountid' />
                                    <attribute name='name' />
                                    <order attribute='name' descending='false' />
                                    <filter type='and'>
                                      <condition attribute='name' operator='like' value='%{0}%' />
                                    </filter>
                                  </entity>
                                </fetch>";
            fetchXml = string.Format(fetchXml, XmlHelper.Encode(term));
            OrganizationServiceProxy.BeginRetrieveMultiple(fetchXml, delegate(object result)
            {
                EntityCollection fetchResult = OrganizationServiceProxy.EndRetrieveMultiple(result, typeof(Entity));
                callback(fetchResult);
            });
        }
```

`customerid` is in the `OpportunityLineItemEditorViewModel` constructor's `Lines.FetchXml`.

I don't have any validation rules at all.

**Comment by scottdurow** [comment]
The metadata on an Entity should only be set for numeric types where Javascript can't tell what it is using it's object type. Can you remove the EntityReference and string metadata. I tried the sample you sent and by removing these lines it worked ok.

**Comment by BobHatcher** [comment]
Taking out the line
```C#
            this.CustomerId.SetValue(InnerOpportunity.CustomerId);
```
didn't work for me - when I try to change the Lookup value I get a blank.

Rummaging around, I put in a ValidationRule on the OwnerId:
```C#
public static ValidationRules OwnerId(ValidationRules rules, object viewModel, object dataContext)
        {

            Opportunity self = Knockout.UnwrapObservable<Opportunity>(viewModel);
            return rules
                   .AddRule("Owner can not be empty.", delegate(object value)
                   {
                       if (value == null)
                           return false;
                       else
                           return true;
                   }
               );

        }
```

Basically, if I try to make the Owner blank it should error. When I change the value of the column - I search for a name and select one, the validation rule fires and says it can't be blank. F12 confirms `value` in that method is null. So I'm deducing that the Lookup value is being set to null somewhere.

That said, since you said it worked for you I'm wondering if the issue is versioning/environmental. I am using the 5.2.5 managed package you provided.

**Comment by scottdurow** [comment]
Could you send me your code again - I didn't see an ownerid column in the version you sent before.

**Comment by BobHatcher** [comment]
The OneDrive link I sent yesterday is live.. resending.

**Comment by BobHatcher** [comment]
... And the ownerid column I had commented out in an attempt to simplify things.

**Comment by scottdurow** [comment]
The problem lies with the value of the idAttribute columns you've used. It should be the attribute name that contains the id value in the Search Results rather than the attribute that the column is bound to:
```XrmLookupEditor.BindColumn(
 GridDataViewBinder.AddColumn(columns, "Owner", 150, "ownerid"),
 vm.OwnerSearchCommand, "systemuserid", "fullname", "");

XrmLookupEditor.BindColumn(
 GridDataViewBinder.AddColumn(columns, "Customer", 150, "customerid"),
 vm.CustomerSearchCommand, "id", "name", "");```

**Comment by BobHatcher** [comment]
Thank you, this partially solved my issue - for the customerid and the custom Lookup.

However the Owner command still isn't working - I tinkered with some of the id values. I also tried using `owninguser` instead of `ownerid`.

Have you ever used the Sparkle grid editor to directly change the `ownerid` of a record? Normally you're supposed to use [AssignRequest](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.assignrequest(v=crm.5).aspx) and I've found some forum posts claiming that you can't directly update the `ownerid` attribute.

**Comment by scottdurow** [comment]
You can't assign by using the update Request - you have to use the Assign Request (we don't have this in SparkleXRM yet - see #1 that still hasn't been done! ) but you can implement it using RegisterExecuteMessageResponseType. See the following example - https://github.com/scottdurow/SparkleXrm/commit/2317b0ef5b280fe1174936c8dce6f3f442829811

**Comment by BobHatcher** [comment]
Worked! Genius.

Thanks again!

**Comment by scottdurow** [comment]
A pull request to get this message in the master would be very well received!

**Comment by BobHatcher** [comment]
I will try to find some time to do that - it's the least I can do for you.
