### ISSUE TITLE
CrmSvcUtil Generated Model Error: The assembly 'Configuration.dll' is not a valid script assembly.

### ISSUE THREAD

**Issue by swofford77** [scottdurow/SparkleXrm#57]
I am assuming that we cannot use the CrmSvcUtil classes and have to roll our own? When I try to reference a class library with a generated class from CrmSvcUtil I receive the following error: The assembly 'Configuration.dll' is not a valid script assembly.

**Comment by scottdurow** [comment]
You are right. The CrmSvcUtil generated classes are too heavyweight anyway. I tend to use a custom code gen templates. I'll get around to publishing them one of these days!
