### ISSUE TITLE
Negative values with decimal and integer are in parentheses

### ISSUE THREAD

**Issue by dos757** [scottdurow/SparkleXrm#58]
Good morning, 

I have an issue with Sparkle XRM (v5.2.6) wich is the last version. 
When i put a negative value like -100 or -230€, the negative symbol is automatically replaced by parentheses. For exemple if i put -100€ ,i get this result ==> €(100). 

I've tried to check my region and language settings but it's correctly configurated with -XX 

I really don't know what's happen with the negative values. This is happening with all type of field (currency, number, decimal ect...) 

Thank you in advance for your help. 

Best regards,

Jean-Michel

**Comment by scottdurow** [comment]
What settings do you have in 'Set Personal Options'->Formats?

SparkleXRM reads your user settings and uses the format strings from there.

**Comment by dos757** [comment]
Hello scott, 

Thanks for the reply. 

The settings are ==> Number : 123 456 789,0000   and Currency : 123 456 789, 00€

Thanks for your help. 

Best regards,

Jean-Michel

**Comment by scottdurow** [comment]
So in your personal options does the Currency Format Preview show the Negative Value as -€123 456 789,0000?

**Comment by scottdurow** [comment]
You'll need to click the 'Customize' button to see this.

**Comment by dos757** [comment]
Here's the screen that show the personnal options. 

![settings01](https://cloud.githubusercontent.com/assets/12613374/8430187/50731e52-1f2f-11e5-999d-4ce0f6c138ee.png)

**Comment by dos757** [comment]
Here's the details for the currency options : 

![settings02](https://cloud.githubusercontent.com/assets/12613374/8430199/98bf57fc-1f2f-11e5-9aeb-0b51741328ca.png)

**Comment by scottdurow** [comment]
Ok - that's all good then.
Make sure that you make a call to  `OrganizationServiceProxy.GetUserSettings();` before you do any DataGrid binding. 
For an example see https://github.com/scottdurow/SparkleXrm/blob/5eea0900c7f0cddfe1d531d1a7a82338755b6f45/SparkleXrmSource/Client/InlineSubGrids/Views/SimpleEditableGridView.cs#L32

**Comment by dos757** [comment]
Thanks scott, 

I'll try to check it tomorrow and i'll comeback to you as soon as possible. 

Thanks again for your help. 

Best regards, 

Jean-Michel

**Comment by dos757** [comment]
Scott, 

Finally, we just added the call to OrganizationServiceProxy.GetUserSettings();
This is now working perfectly. 

Thanks for your help and your reactivity about this issue. 


Best regards,

Jean-Michel
