### ISSUE TITLE
Can't open SampleProject (incompatible) 

### ISSUE THREAD

**Issue by mm3058** [scottdurow/SparkleXrm#60]
I can't open project that you use in: Part 1: Setting up a new SparkleXrm Project.

I have installed VS Ultimate 2012 with update 4, Dynamics CRM 2015 SDK and ScriptSharp.

![sparklexrm](https://cloud.githubusercontent.com/assets/9011654/8957175/dc9fad12-35fc-11e5-8350-20a2927086a2.png)

Am I doing something wrong?

Thanks!

**Comment by scottdurow** [comment]
Have you installed the Dynamics CRM 2015 VS Developer Toolkit?

**Comment by mm3058** [comment]
Yes, that was a problem. I couldn't find CRM 2015 Developer Toolkit, if you have link can you please shere? Then I installed CRM 2015 Developer Toolkit and it works.

**Comment by scottdurow** [comment]
Sorry I meant the CRM2013 version found here - https://www.microsoft.com/en-gb/download/details.aspx?id=40321

There isn't a CRM2015 version available yet.
