### ISSUE TITLE
Grid Editor - ClientUI.js Gives Script Error on CRM for Phones

### ISSUE THREAD

**Issue by BobHatcher** [scottdurow/SparkleXrm#61]
When ClientUI.js is included as a Web resource on a CRM 2015 form, the CRM For Phones app throws a script error.

This is a problem as it does not appear possible to create a mobile-only form.

Including the JS from within the grid's Web Resource hides it from the mobile app, but disables the Save button.

I'm trying to find a workaround to make ClientUI.js not visible to the mobile app.

**Comment by BobHatcher** [comment]
Hold on, might have spoken too soon.. sorry can't delete this post. Will follow up when I know more.

**Comment by scottdurow** [comment]
Hi Bob - did you get anymore info on this?

**Comment by BobHatcher** [comment]
I apologize, I promised I'd follow up and then never did. This one was a false alarm - I wish GitHub could let me delete posts!

**Comment by scottdurow** [comment]
Great news - thanks,
