### ISSUE TITLE
XrmDateEditor for grid does not support date and time, just date-only

### ISSUE THREAD

**Issue by jeff-goodson-celedonpartners** [scottdurow/SparkleXrm#66]
Despite providing a .FormatterDateAndTime, and despite having a boolean "dateOnly" parameter in the BindColumn method, the implementation ignores said dateOnly parameter (which is good, because there is no CrmDateTimeEditor to correspond with the CrmDateEditor.

At the least passing "false" should result in a NotImplementedException until such time as the implementation is available.

**Comment by scottdurow** [comment]
Good point - ideally the time editor should be implemented. I've not needed it yet - but I'll make this a priority.

**Comment by tinunelson** [comment]
Scott, any plans to add time editor or is there any workaround.?

**Comment by scottdurow** [comment]
The workaround at this time to use a separate column for the time element.

**Comment by KK1674** [comment]
Scott,
Do you have any plan to implement time editor in grid?

**Comment by KK1674** [comment]
Scott,

How can we show time element in separate column?
