### ISSUE TITLE
CrmPackage, Plugin and Workflow project are incompatible with VS2012 when Open the solution

### ISSUE THREAD

**Issue by walcivar** [scottdurow/SparkleXrm#67]
Hi Scott

Today I downloaded the SparkleXrm solution to make a editable grid in my Dynamics CRM instance (2015), I have VS2012, the Developer Toolkit for VS2012 and Script# v0.7.5  installed. As you can see I have the requirements to start working with this framework.

But I have a problem, when I open the solution throw and error saying that the CrmPackage, Plugin and Wokflow projects are incompatibles so I can not run the solution to connect it whit my CRM instance,

How I can solve this problem?, I downloaded the last version of SparkleXrm, is there a new link to download? please help!!!

Regards
Wilmer Alcivar

**Comment by walcivar** [comment]
Hi Scott

An image of this issue:

![image](https://cloud.githubusercontent.com/assets/5630463/9707029/62235806-54d1-11e5-8c4a-467f5c3bb94a.png)

**Comment by scottdurow** [comment]
Do you have the CRM2013 version of the toolkit installed? Also, when you create a new project - what ProjectTypeGuid does it get - compare to - https://github.com/scottdurow/SparkleXrm/blob/master/SparkleXrmSamples/SparkleXrmTemplateCRM2015/SparkleXrmCrmPackage/CrmPackage/CrmPackage.csproj#L9

**Comment by walcivar** [comment]
Hi Scott

I downloaded the correct version of the developer toolkit for VS2012 and the problem is solved
Thank you for your help
