### ISSUE TITLE
Set up script# project to have different js file for each html web resource

### ISSUE THREAD

**Issue by awisey** [scottdurow/SparkleXrm#69]
Is it possible to set up the script# project so that you can have different js files generated for each html webresource and not have one large js file for different html webresources?

**Comment by scottdurow** [comment]
Yes - you just have to have multiple ClientUI projects and set a different unique name for the script generated.

**Comment by awisey** [comment]
Thank you for the prompt response, you've made a great framework!

Where do you set this unique name?

I'm not to familiar with script# and documentation is a little thin. Would be nice to have an example of using your dazzling sparkle framework without the use of script#.

**Comment by scottdurow** [comment]
You set the unique name in the Developer Toolkit webresource properties for the ClientUI.js. So although the name is still ClientUI.js when compiled - the name in CRM is whatever you set it to be.

If you can come up with some samples that would be great - I know some folks want to use it with TypeScript.
