### ISSUE TITLE
Error when using XrmTimeEditor 

### ISSUE THREAD

**Issue by tinunelson** [scottdurow/SparkleXrm#75]
I am trying to use "XrmTimeEditor" binding to a datetime field in a grid. But after deployment the grid is not loading and in debug it is showing error" Uncaught TypeError: Cannot read property 'timeformatstring' of null".  Any help would be appreciated..!   

Below given is the line where it is throwing error..

" SparkleXrm.GridEditor.XrmTimeEditor.bindColumn=function(column){column.editor=SparkleXrm.GridEditor.XrmTimeEditor.timeEditor;column.formatter=SparkleXrm.GridEditor.XrmTimeEditor.formatter;column.options=Xrm.Sdk.OrganizationServiceProxy.userSettings.timeformatstring;return column;} "

**Comment by tinunelson** [comment]
I missed "OrganizationServiceProxy.GetUserSettings()".... Solved....

**Comment by scottdurow** [comment]
Thanks for letting us know - glad it's sorted.
