### ISSUE TITLE
Change Lookup field value dynamically based on the previous column selected.

### ISSUE THREAD

**Issue by tinunelson** [scottdurow/SparkleXrm#76]
Hi Scott,
I wanted to know if the following feature is possible in a grid Lookup field.

In a grid, first column will be an "option set" with option to select Account or Lead. As per the selection, in the next Lookup field I should be able to select either accounts or lead.

If you have any example related to this please share...

Thanks and regards,
Tinu Nelson

**Comment by scottdurow** [comment]
Yes - you could do this by simply using the optionset value to control the search callback. 
You can see an example of this in the Connection UI sample where the Role lookup is dependent on the type of record that is selected in another column.

See https://github.com/scottdurow/SparkleXrm/blob/master/SparkleXrmSamples/ConnectionsUI/ClientUI/ViewModel/ObservableConnection.cs#L124

**Comment by tinunelson** [comment]
Great.. Thanks for the help. I am now able to do this. 

But I am facing an issue.  In my case I am using a single lookup in the grid to show data from different lookup like Account and Lead. I am able to load from different lookup and show the data as you mentioned in the earlier post. But when I am saving, it is causing error. 

eg:- In the below code, I want to change the field from "new_leadvisit" to "new_accountvisit" when I am selecting an account in the previous option set . Is it possible.?? Hope you understood the question..


 XrmLookupEditor.BindColumn(
               GridDataViewBinder.AddColumn(columns, "ABC", 150,"new_leadvisit"),
               vm.Command, "id", "col0,col1,col2,col3", ""); 

Thanks and regards,
Tinu Nelson

**Comment by scottdurow** [comment]
You will need to pre-process your records before they are saved - remove the attribute that is linked to the lookup and then set the correct attribute according to the entity reference logical Name.

**Comment by tinunelson** [comment]
Thanks for the replay. I will try your suggestion...
