### ISSUE TITLE
Form Fields not working (save,Delete,Move up,MoveDown) - Quote Line Editor

### ISSUE THREAD

**Issue by gvkn009** [scottdurow/SparkleXrm#78]
[Client.txt](https://github.com/scottdurow/SparkleXrm/files/38620/Client.txt)
[QuotelineEditor.txt](https://github.com/scottdurow/SparkleXrm/files/38621/QuotelineEditor.txt)

I am able to retrieve the data but not able to save,add or delete.

Your help will be appreciated.

Thanks,

Venkata

**Comment by scottdurow** [comment]
Duplicate of #77
