### ISSUE TITLE
How to create a grid with column headers which are nested within category headers.

### ISSUE THREAD

**Issue by tinunelson** [scottdurow/SparkleXrm#80]
Can we add a category header in subgrid as shown in the attached screenshot (Stock Price)? If you have any code sample, please share..

![capture](https://cloud.githubusercontent.com/assets/15125912/11465967/abcd1440-9763-11e5-82a0-82ebedafb83c.JPG)

Thanks,
Tinu Nelson

**Comment by scottdurow** [comment]
The general premise of SparkleXRM is not to steer too far away from the native Dynamics CRM UX.
That said, there is a fork of SlickGrid with header grouping which you could easily encorporate http://hariharanpalani.github.io/SlickGrid/examples/example-HeaderGrouping.htm
