### ISSUE TITLE
Is there a way to add a button in each row of the inline editable grid

### ISSUE THREAD

**Issue by gvkn009** [scottdurow/SparkleXrm#82]

**Comment by scottdurow** [comment]
Definitely. 
You would need to create a custom column formatter to show the button similar to https://github.com/scottdurow/SparkleXrm/blob/master/SparkleXrmSamples/MultiEntitySearch/ClientUI/Views/MultiSearchView2013.cs#L135

Then you would add a click handler to pickup an attribute on the button (Set by the formatter) that specifies the data for the row similar to https://github.com/scottdurow/SparkleXrm/blob/ebd4a3579cf656fc38a26119f781fbe781f0c9ec/SparkleXrmSource/SparkleXrmUI/GridEditor/GridDataViewBinder.cs#L208

**Comment by gvkn009** [comment]
Thanks scott.will try it .

**Comment by scottdurow** [comment]
How did you get on?

**Comment by gvkn009** [comment]
Scott,

I did it exactly the way you told me.It worked absolutely fine.

Thanks a lot.

Regards,

Venkata Gunturu
