### ISSUE TITLE
ConnectionUI, Unit Test

### ISSUE THREAD

**Issue by mbeauchamp7** [scottdurow/SparkleXrm#85]
Hi, I'm starting to get the grip of your tutorial and like it more and more!

But I was trying to run the unit test with all of your code to try and run the tests and got an error I can't figure out how to fix.

![image](https://cloud.githubusercontent.com/assets/15185355/11966939/f42eb53e-a8cc-11e5-958c-b0ccbe08c117.png)

Thank you for your time!

**Comment by scottdurow** [comment]
This is a regression issue after adding in the localisation support. The issues is that the Resource Strings are not defined in the unit tests. You can easily resolve this by giving the ResourceStrings.RequiredMessage a non null value:
public static string RequiredMessage="Required";

I've created issue #89 to report this error in a more friendly way!
